language: python
python:
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install -y libspatialindex-dev
  - sudo apt-get install -y texlive-xetex
  - pip install pipenv
install:
  - pipenv install
script:
  - python -m unittest discover -v