from hipparcos import build_hipparcos_database
from hyg import build_hyg_database
from constellations import build_constellation_database

build_constellation_database()
build_hipparcos_database()
build_hyg_database()